version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: client-nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: markCole256
    ports:
      - "5436:5432"
    volumes:
      - pgdata_notification:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6383:6379"
volumes:
  pgdata_notification:
